#!/bin/bash
# todo no use for now, don't know why
chown -R ubuntu /etc/salt /var/cache/salt /var/log/salt /var/run/salt /srv /etc/salt/pki

repo_path=/srv/tsplk-formula
script_path=/script/master-bootstrap.sh
# git clone
git clone https://github.com/splksusqa/tsplk-formula.git ${repo_path}

# run script
chmod +x ${repo_path}${script_path}
source ${repo_path}${script_path}
