#!/bin/bash
# todo no use for now, don't know why
chown -R ubuntu /etc/salt /var/cache/salt /var/log/salt /var/run/salt /srv /etc/salt/pki

# sync formula itself first
salt-call \
    --log-file=/var/log/tsplk.log \
    --log-file-level=warning \
    --file-root=/srv/tsplk-formula/salt \
    --local \
    state.apply tsplk-formula \
    pillar='{"tsplk": {"tsplk-formula": {"version": "${tsplk_formula_version}"}}}'

# config salt master with latest tsplk-formula
salt-call \
    --log-file=/var/log/tsplk.log \
    --log-file-level=warning \
    --file-root=/srv/tsplk-formula/salt \
    --local \
    state.apply tsplk-master-bootstrap \
    pillar='{"tsplk": {"user": "${user}", "project": "${project}"}}'

# use /etc/minion as configuration and it's pillar data to run
# spin-up minion, provisioning, sending message, after master is configured
salt-call \
    --log-file=/var/log/tsplk.log \
    --log-file-level=warning \
    --file-root=/srv/tsplk-formula/salt \
    --local \
    state.apply tsplk-run
